### ISSUE TITLE
Zero division error

### ISSUE THREAD

**Issue by WoosterUK** [numbas/blackboard-scorm-analysis#1]
I am getting a divide by zero error (see gist, https://gist.github.com/anonymous/034f3bfb629642ee0680) when I try to run a report on a recent quiz, or to click on any question to view the transcript. One possible cause is that I set up a zero mark question as part of the quiz (it was an opportunity for students to feed back a question to me for answering in lectures).

Am running this on Linux Mint 17.3, with Python 3.4.3 and up-to-date versions of required packages.

**Comment by christianp** [comment]
Thanks for the report.
I've just made a change - can you pull that and tell me if it fixes the problem?

**Comment by WoosterUK** [comment]
Yep, that solves it! Thanks!
