### ISSUE TITLE
UTC formatting in dates

### ISSUE THREAD

**Issue by andy-iskauskas** [numbas/blackboard-scorm-analysis#4]
It seems that the datestamps that come from Blackboard now have an additional UTC identifier at the end of their string, which gives a 'unconverted data remains' error when server.py is called. In L98 of blackboardscorm.py, I think changing '%Y-%m-%dT%H:%M:%S' to '%Y-%m-%dT%H:%M:%S.%fZ' should fix it.

**Comment by christianp** [comment]
Thanks for reporting this, and the fix!
